controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    bravo_7_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    bravo_7_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

bravo_7_position_controller:
  ros__parameters:
    joints:
      - bravo_axis_g
      - bravo_axis_f
      - bravo_axis_e
      - bravo_axis_d
      - bravo_axis_c
      - bravo_axis_b

    command_interfaces:
      - position

    state_interfaces:
      - position
    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

bravo_7_hand_controller:
  ros__parameters:
    joints:
      - bravo_axis_a
    command_interfaces:
      - position

    state_interfaces:
      - position
    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

forward_position_controller:
  ros__parameters:
    joints:
      - bravo_axis_g
      - bravo_axis_f
      - bravo_axis_e
      - bravo_axis_d
      - bravo_axis_c
      - bravo_axis_b